"""add respondent profile fields

Revision ID: 169d03e72a66
Revises: f1fdaa1a54de
Create Date: 2026-02-14 17:21:01.458406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169d03e72a66'
down_revision = 'f1fdaa1a54de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respondents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_optional', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('semester', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('used_ai', sa.Boolean(), nullable=True))
        batch_op.drop_column('batch_year')
        batch_op.drop_column('education_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respondents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education_level', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('batch_year', sa.INTEGER(), nullable=True))
        batch_op.drop_column('used_ai')
        batch_op.drop_column('semester')
        batch_op.drop_column('name_optional')

    # ### end Alembic commands ###
