"""init tables

Revision ID: f1fdaa1a54de
Revises: 
Create Date: 2026-02-08 08:18:45.715741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1fdaa1a54de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('respondents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('university', sa.String(length=150), nullable=True),
    sa.Column('major', sa.String(length=150), nullable=True),
    sa.Column('education_level', sa.String(length=10), nullable=True),
    sa.Column('batch_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionnaire_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('respondent_id', sa.String(length=36), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('answers_json', sa.JSON(), nullable=False),
    sa.Column('data_version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['respondent_id'], ['respondents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clustering_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('response_id', sa.String(length=36), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('segment_label', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['questionnaire_responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('response_id', sa.String(length=36), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('predicted_label', sa.String(length=50), nullable=False),
    sa.Column('proba_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['questionnaire_responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction_results')
    op.drop_table('clustering_results')
    op.drop_table('questionnaire_responses')
    op.drop_table('respondents')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
